#!/usr/bin/env python3
"""Generate build/cursors.bin + build/cursors.h from kora/cursors/<theme>-<kind>.png.

The cursors are REAL raster images ("photos") - downloaded web cursor art,
auto-cropped to the opaque bounding box and LANCZOS-downscaled to 32x32 so
they stay smooth (anti-aliased alpha).  Hotspots are computed from the
crop geometry (arrow tip / finger tip ~ top-left of the bbox).

Blob format (little-endian):
    offset 0:  "YCRS" u16 version=1 u16 n_themes u16 n_kinds u16 pad   (16 B)
    entries:   n_themes * n_kinds x { char name[16]; u16 w,h; u16 hotx,hoty; u32 off; }
    pixels:    RGBA rows, pitch = w*4, per entry at off
Kinds are fixed: 0 = arrow, 1 = hand.
File naming:  kora/cursors/<theme>-<kind>.png   (kind in {arrow, hand})
"""
import os, struct, sys

ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC    = os.path.join(ROOT, "kora", "cursors")
OUT_B  = os.path.join(ROOT, "build", "cursors.bin")
OUT_H  = os.path.join(ROOT, "build", "cursor_assets.h")
SZ     = 32          # output cursor size (px)
KINDS  = [("arrow", 0), ("hand", 1)]
KIND_N = 2

def main():
    from PIL import Image
    # discover themes: <theme>-arrow.png must exist
    themes = []
    for fn in sorted(os.listdir(SRC)):
        if not fn.endswith("-arrow.png"):
            continue
        theme = fn[: -len("-arrow.png")]
        if theme.startswith("."):
            continue
        themes.append(theme)
    if not themes:
        print("ERROR: no kora/cursors/*-arrow.png found", file=sys.stderr)
        sys.exit(1)

    bin_data = bytearray()
    bin_data += b"YCRS" + struct.pack("<HHHH", 1, len(themes), KIND_N, 0)
    n_entries = len(themes) * KIND_N
    bin_data += b"\x00" * (28 * n_entries)     # entry table placeholder

    entries = []
    missing = 0
    for t in themes:
        for kind, kidx in KINDS:
            fn = os.path.join(SRC, f"{t}-{kind}.png")
            name = f"{t}-{kind}"
            if not os.path.exists(fn):
                print(f"MISSING cursor: {fn}", file=sys.stderr)
                missing += 1
                entries.append((name, 1, 1, 0, 0, 0))
                continue
            im = Image.open(fn).convert("RGBA")
            bbox = im.getbbox()                # alpha bbox
            if not bbox:
                missing += 1
                entries.append((name, 1, 1, 0, 0, 0))
                continue
            x0, y0, x1, y1 = bbox
            crop = im.crop((x0, y0, x1, y1))
            cw, ch = crop.size
            # scale down to fit SZ, keeping aspect; letterbox on transparent
            sc = min(SZ / cw, SZ / ch)
            nw = max(1, int(round(cw * sc)))
            nh = max(1, int(round(ch * sc)))
            small = crop.resize((nw, nh), Image.LANCZOS)
            canvas = Image.new("RGBA", (SZ, SZ), (0, 0, 0, 0))
            canvas.paste(small, ((SZ - nw) // 2, (SZ - nh) // 2), small)
            px = canvas.load()
            raw = bytearray()
            for y in range(SZ):
                for x in range(SZ):
                    r, g, b, a = px[x, y]
                    raw += bytes((r, g, b, a))
            # hotspot: arrow/finger tip ~ top-left of the CROPPED image
            # + a small inset (cropped coords, scaled to output size)
            off = len(bin_data)
            bin_data += raw
            hotx = max(0, min(SZ - 1, int((cw * 0.06) * sc)))
            hoty = max(0, min(SZ - 1, int((ch * 0.06) * sc)))
            entries.append((name, SZ, SZ, hotx, hoty, off))

    # fill the entry table
    for i, (name, w, h, hotx, hoty, off) in enumerate(entries):
        b = name.encode()[:16].ljust(16, b"\x00")
        bin_data[16 + i * 28: 16 + i * 28 + 16] = b
        struct.pack_into("<HHHH", bin_data, 16 + i * 28 + 16, w, h, hotx, hoty)
        struct.pack_into("<I",  bin_data, 16 + i * 28 + 24, off)

    os.makedirs(os.path.dirname(OUT_B), exist_ok=True)
    with open(OUT_B, "wb") as f:
        f.write(bin_data)

    names = ", ".join(f'"{t}"' for t in themes)
    with open(OUT_H, "w") as f:
        f.write("/* Auto-generated by scripts/gen_cursors.py */\n")
        f.write("#pragma once\n")
        f.write(f"#define CURSOR_THEME_COUNT {len(themes)}\n")
        f.write("#define CURSOR_KIND_ARROW 0\n")
        f.write("#define CURSOR_KIND_HAND 1\n")
        f.write(f"#define CURSOR_KIND_COUNT {KIND_N}\n")
        f.write(f"#define CURSOR_THEME_NAMES {{ {names} }}\n")
        f.write(f"#define CURSOR_SIZE {SZ}\n")
    print(f"cursors: {len(themes)} theme(s) [{', '.join(themes)}], "
          f"{len(bin_data)} bytes -> cursors.bin + cursor_assets.h")

if __name__ == "__main__":
    main()
