#!/usr/bin/env python3
"""
Yart OS - render *multiple* 8x16 bitmap fonts and emit a font registry
so the system can switch fonts on demand.

Output: kernel/gui/font_data.c containing:
   const u8 yart_font_default[256][16];
   const u8 yart_font_mono[256][16];
   const u8 yart_font_term[256][16];
   const yart_font_t yart_fonts[];
   const int yart_fonts_count;
"""
import os, sys
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16
THRESHOLD = 128

FONTS = [
    ("default", "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"),
    ("mono",    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"),
    ("term",    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"),
]

def render_set(path):
    for sz in (16, 15, 14, 13, 12, 11):
        fnt = ImageFont.truetype(path, sz)
        max_w = 0
        for cp in range(0x21, 0x7F):
            bb = fnt.getbbox(chr(cp))
            if bb: max_w = max(max_w, bb[2] - bb[0])
        asc, desc = fnt.getmetrics()
        if max_w <= W and asc + desc <= H + 2:
            break
    glyphs = {0x20: [0]*H}
    for cp in range(0x21, 0x7F):
        ch = chr(cp)
        img = Image.new("L", (W, H), 0)
        d = ImageDraw.Draw(img)
        bbox = fnt.getbbox(ch)
        if not bbox or bbox[2] - bbox[0] == 0:
            glyphs[cp] = [0]*H
            continue
        ch_w = bbox[2] - bbox[0]
        x0 = (W - ch_w) // 2 - bbox[0]
        y0 = 2 - bbox[1] + (asc - (bbox[3] - bbox[1])) // 4
        d.text((x0, y0), ch, font=fnt, fill=255)
        rows = []
        px = img.load()
        for y in range(H):
            b = 0
            for x in range(W):
                if px[x, y] > THRESHOLD:
                    b |= (1 << (7 - x))
            rows.append(b)
        glyphs[cp] = rows
    return glyphs, sz

def fallback():
    rows = [0]*H
    for y in range(7, 11):
        rows[y] = 0b00111100
    return rows

def main(out):
    f = open(out, "w")
    f.write('/* AUTO-GENERATED by scripts/gen_fonts.py */\n')
    f.write('#include <yart/types.h>\n#include <yart/gui.h>\n\n')
    for name, path in FONTS:
        glyphs, sz = render_set(path)
        f.write(f"/* font {name!r} from {os.path.basename(path)} @ {sz}pt */\n")
        f.write(f"const u8 yart_font_{name}[256][16] = {{\n")
        for cp in range(256):
            rows = glyphs.get(cp, fallback()) if 0x20 <= cp < 0x7F else fallback()
            f.write(f"  {{ {','.join(f'0x{b:02X}' for b in rows)} }},\n")
        f.write("};\n\n")
    # Registry
    
    f.write("const yart_font_t yart_fonts[] = {\n")
    for name, _ in FONTS:
        f.write(f'  {{ "{name}", yart_font_{name} }},\n')
    f.write("};\n")
    f.write(f"const int yart_fonts_count = {len(FONTS)};\n\n")
    # Live pointer - the active font, swapped by fb_set_font()
    f.write("const u8 (*yart_font8x16)[16] = yart_font_default;\n")
    f.close()
    print("wrote", out)

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "kernel/gui/font_data.c")
